### PR TITLE
feat(history): notification history

### PR DESCRIPTION
**Pull request by BombayV**
## Features
- History UI.
- Filter through notifications.
- Filter types.
- Old notifications displaying info (style, title, icon, message, hour/date).
- History exports for creating your own history.

_Anyone who tests this. Please let me know any issues._

### CODE REVIEW

**Comment by TasoOneAsia** [comment]
Will get around to reviewing this sometime this week

**Comment by BombayV** [comment]
No worries. I'm also waiting for @Legacy-TacticalGamingInteractive to test it.

**Comment by BombayV** [comment]
This will have to wait as I have yet to fix the error with markdown tags.

**Comment by Legacy-TacticalGamingInteractive** [comment]
**Unable to close history TypeError: Failed to fetch (@t-notify/nui/assets/script.js:132)**

**Comment by Legacy-TacticalGamingInteractive** [comment]
image

For reference. Here is my code.

`
        TriggerServerEvent('911', getPostal, location, msg, x, y, z)
		exports['t-notify']:Custom({
			style = 'error',
			duration = 25000,
			title = 'Dispatch: Incoming 911 Call',
			message = ' ** >>   < **' .. getPostal .. '** ' .. StreetName .. '** \n---\n ** ' .. msg,
			image = 'imagename.png',			
			sound = true
		})
    end
end)`

**Comment by Legacy-TacticalGamingInteractive** [comment]
I've made some progress...

image

**Comment by Legacy-TacticalGamingInteractive** [comment]
Though it still doesn't like anytime you add formatting for other options
image

**Comment by BombayV** [comment]
@Legacy-TacticalGamingInteractive You're free to test this now. It should work fine now. Report back if you find any errors.

**Review by Legacy-TacticalGamingInteractive — APPROVED** [review]

**Review by Legacy-TacticalGamingInteractive — APPROVED** [review]
Appreciate it!

**Comment by RockySouthpaw** [comment]
> Will get around to reviewing this sometime this week

68 weeks 5 days

**Pull request merged**
