### PR TITLE
Add possibility for custom positioning per notification

### PR DESCRIPTION
**Pull request by xnubil**
I added this to my server so I can position certain notifications at a different spot on screen as needed. Pull request if you want to implement as well

### CODE REVIEW

**Comment by TasoOneAsia** [comment]
Do you mind updating this PR with the latest master as well as inline documentation for the position parameter like the others?

**Comment by xnubil** [comment]
On it. Sorry about that

**Comment by TasoOneAsia** [comment]
Thanks, I'll be integrating these changes into the newest build on the UPD branch shortly.

**Comment by TasoOneAsia** [comment]
This commit adds the position option 5b1df4a938e274c5cddf6baaf5cf436d31f55b04. Does it reflect your changes adequately? I see you also altered the structure of the sound parameter as well to accept per notification specifications. I have yet to port that to the UPD.

**Comment by xnubil** [comment]
Yes reflects changes perfectly.  I did add a sound option per message as well. Forgot to add that to my commit message as well

**Comment by TasoOneAsia** [comment]
All of your proposed changes have been integrated into 7dda9e09dbae7c4c2539f9f4ed5f262c245189c4. Thanks for the PR 😄

**Pull request closed without merging**
