### PR TITLE
feat: allow updating of an existing persistent notification

### PR DESCRIPTION
**Pull request by emileet**
quick addition to allow an existing persistent notification to be updated

### CODE REVIEW

**Comment by TasoOneAsia** [comment]
Thanks for the pull request, would you be able to add the update action to the docs as well? Aside from that the rest of this looks good!

**Comment by emileet** [comment]
no problemo

**Comment by emileet** [comment]
alrighty, should be good to go :)

**Comment by TasoOneAsia** [comment]
Thanks for following all the code styling :), i’ll do some final testing, merge & create a minor semver release tonight

**Comment by TasoOneAsia** [comment]
Merged into master with 564a618a8dfd562ca190aa5646b180d420eec261

**Pull request closed without merging**
